[2025-01-12T16:46:58.556+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.ft_posting_f manual__2025-01-12T16:46:53.731956+00:00 [queued]>
[2025-01-12T16:46:58.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.ft_posting_f manual__2025-01-12T16:46:53.731956+00:00 [queued]>
[2025-01-12T16:46:58.573+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-12T16:46:58.784+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ft_posting_f> on 2025-01-12 16:46:53.731956+00:00
[2025-01-12T16:46:58.794+0000] {standard_task_runner.py:60} INFO - Started process 4080 to run task
[2025-01-12T16:46:58.798+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'ft_posting_f', 'manual__2025-01-12T16:46:53.731956+00:00', '--job-id', '2370', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmphfc0hzlp']
[2025-01-12T16:46:58.802+0000] {standard_task_runner.py:88} INFO - Job 2370: Subtask ft_posting_f
[2025-01-12T16:46:58.867+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.ft_posting_f manual__2025-01-12T16:46:53.731956+00:00 [running]> on host 711845a6becd
[2025-01-12T16:46:58.970+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='ft_posting_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T16:46:53.731956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T16:46:53.731956+00:00'
[2025-01-12T16:46:59.022+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T16:46:59.956+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-12T16:46:59.964+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_date, task_id=ft_posting_f, execution_date=20250112T164653, start_date=20250112T164658, end_date=20250112T164659
[2025-01-12T16:46:59.967+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T16:47:00.012+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO log.logt (execution_datetime, event_datetime, event_name)
        VALUES ('2025-01-12 16:46:53.731956', '2025-01-12T16:46:59.965382', 'ft_posting_f');
    , parameters: None
[2025-01-12T16:47:00.015+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-12T16:47:00.054+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-12T16:47:00.080+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
