[2025-01-10T15:44:35.403+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.sql_md_currency_d manual__2025-01-10T15:44:28.762833+00:00 [queued]>
[2025-01-10T15:44:35.415+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.sql_md_currency_d manual__2025-01-10T15:44:28.762833+00:00 [queued]>
[2025-01-10T15:44:35.415+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-10T15:44:35.601+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_md_currency_d> on 2025-01-10 15:44:28.762833+00:00
[2025-01-10T15:44:35.608+0000] {standard_task_runner.py:60} INFO - Started process 2362 to run task
[2025-01-10T15:44:35.618+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'sql_md_currency_d', 'manual__2025-01-10T15:44:28.762833+00:00', '--job-id', '1761', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpw_n5m3_y']
[2025-01-10T15:44:35.621+0000] {standard_task_runner.py:88} INFO - Job 1761: Subtask sql_md_currency_d
[2025-01-10T15:44:35.686+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.sql_md_currency_d manual__2025-01-10T15:44:28.762833+00:00 [running]> on host 711845a6becd
[2025-01-10T15:44:35.773+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='sql_md_currency_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T15:44:28.762833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T15:44:28.762833+00:00'
[2025-01-10T15:44:35.775+0000] {sql.py:276} INFO - Executing:  INSERT INTO ds.md_currency_d(
      currency_rk
    , data_actual_date
    , data_actual_end_date
    , currency_code
    , code_iso_char
)
SELECT mcd."CURRENCY_RK"
    , to_date(mcd."DATA_ACTUAL_DATE", '%Y-%m-%d') 
    , to_date(mcd."DATA_ACTUAL_END_DATE", '%Y-%m-%d')
    , mcd."CURRENCY_CODE" 
	, mcd."CODE_ISO_CHAR" 
FROM stage.md_currency_d mcd
WHERE mcd."CURRENCY_RK" IS NOT NULL
   AND mcd."DATA_ACTUAL_DATE" IS NOT NULL
On conflict on constraint md_currency_d_pkey do update
	set data_actual_end_date=excluded.data_actual_end_date
		,currency_code=excluded.currency_code
		,code_iso_char=excluded.code_iso_char; 
[2025-01-10T15:44:35.787+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-10T15:44:35.800+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-10T15:44:35.851+0000] {sql.py:450} INFO - Running statement:  INSERT INTO ds.md_currency_d(
      currency_rk
    , data_actual_date
    , data_actual_end_date
    , currency_code
    , code_iso_char
)
SELECT mcd."CURRENCY_RK"
    , to_date(mcd."DATA_ACTUAL_DATE", '%Y-%m-%d') 
    , to_date(mcd."DATA_ACTUAL_END_DATE", '%Y-%m-%d')
    , mcd."CURRENCY_CODE" 
	, mcd."CODE_ISO_CHAR" 
FROM stage.md_currency_d mcd
WHERE mcd."CURRENCY_RK" IS NOT NULL
   AND mcd."DATA_ACTUAL_DATE" IS NOT NULL
On conflict on constraint md_currency_d_pkey do update
	set data_actual_end_date=excluded.data_actual_end_date
		,currency_code=excluded.currency_code
		,code_iso_char=excluded.code_iso_char; , parameters: None
[2025-01-10T15:44:35.857+0000] {sql.py:459} INFO - Rows affected: 50
[2025-01-10T15:44:35.869+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_date, task_id=sql_md_currency_d, execution_date=20250110T154428, start_date=20250110T154435, end_date=20250110T154435
[2025-01-10T15:44:35.873+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-10T15:44:35.929+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO log.logt (execution_datetime, event_datetime, event_name)
        VALUES ('2025-01-10T15:44:28.762833', '2025-01-10T15:44:35.870045', 'sql_md_currency_d');
    , parameters: None
[2025-01-10T15:44:35.933+0000] {taskinstance.py:1116} ERROR - Error when executing uploading_logs callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1113, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/insert_data.py", line 51, in uploading_logs
    postgres_hook.run(query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: ОШИБКА:  отношение "log.logt" не существует
LINE 2:         INSERT INTO log.logt (execution_datetime, event_date...
                            ^

[2025-01-10T15:44:35.985+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-10T15:44:36.015+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
