[2025-01-07T10:06:44.340+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.sql_md_account_d manual__2025-01-07T09:51:33.644346+00:00 [queued]>
[2025-01-07T10:06:44.348+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.sql_md_account_d manual__2025-01-07T09:51:33.644346+00:00 [queued]>
[2025-01-07T10:06:44.349+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-01-07T10:06:44.475+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_md_account_d> on 2025-01-07 09:51:33.644346+00:00
[2025-01-07T10:06:44.480+0000] {standard_task_runner.py:60} INFO - Started process 668 to run task
[2025-01-07T10:06:44.482+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'sql_md_account_d', 'manual__2025-01-07T09:51:33.644346+00:00', '--job-id', '775', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmps3cybxp0']
[2025-01-07T10:06:44.484+0000] {standard_task_runner.py:88} INFO - Job 775: Subtask sql_md_account_d
[2025-01-07T10:06:44.524+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.sql_md_account_d manual__2025-01-07T09:51:33.644346+00:00 [running]> on host 25a397655cc7
[2025-01-07T10:06:44.586+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='sql_md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T09:51:33.644346+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T09:51:33.644346+00:00'
[2025-01-07T10:06:44.588+0000] {sql.py:276} INFO - Executing: INSERT INTO dsl.md_account_d( 
     "DATA_ACTUAL_DATE"
    ,"DATA_ACTUAL_END_DATE"
    ,"ACCOUNT_RK"
    ,"ACCOUNT_NUMBER"
    ,"CHAR_TYPE"
	,"CURRENCY_RK"
	,"CURRENCY_CODE"
)
SELECT
	  to_date(fpf."DATA_ACTUAL_DATE", 'dd.mm.YYYY')
    , to_date(fpf."DATA_ACTUAL_END_DATE", 'dd.mm.YYYY') 
    , to_int(fpf."ACCOUNT_RK")
    , to_bigint(fpf."ACCOUNT_NUMBER") 
	, to_char(fpf."CHAR_TYPE")
	, to_int(fpf."CURRENCY_RK") 
	, to_int(fpf."CURRENCY_CODE")
  FROM dsl.md_account_d fpf
 WHERE fpf."DATA_ACTUAL_DATE" IS NOT NULL
   AND fpf."DATA_ACTUAL_END_DATE" IS NOT NULL
   AND fpf."ACCOUNT_RK" IS NOT NULL
   AND fpf."ACCOUNT_NUMBER" IS NOT NULL
   AND fpf."CHAR_TYPE" IS NOT NULL
   AND fpf."CURRENCY_RK" IS NOT NULL
   AND fpf."CURRENCY_CODE" IS NOT NULL; 

[2025-01-07T10:06:44.596+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-07T10:06:44.603+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-07T10:06:44.645+0000] {sql.py:450} INFO - Running statement: INSERT INTO dsl.md_account_d( 
     "DATA_ACTUAL_DATE"
    ,"DATA_ACTUAL_END_DATE"
    ,"ACCOUNT_RK"
    ,"ACCOUNT_NUMBER"
    ,"CHAR_TYPE"
	,"CURRENCY_RK"
	,"CURRENCY_CODE"
)
SELECT
	  to_date(fpf."DATA_ACTUAL_DATE", 'dd.mm.YYYY')
    , to_date(fpf."DATA_ACTUAL_END_DATE", 'dd.mm.YYYY') 
    , to_int(fpf."ACCOUNT_RK")
    , to_bigint(fpf."ACCOUNT_NUMBER") 
	, to_char(fpf."CHAR_TYPE")
	, to_int(fpf."CURRENCY_RK") 
	, to_int(fpf."CURRENCY_CODE")
  FROM dsl.md_account_d fpf
 WHERE fpf."DATA_ACTUAL_DATE" IS NOT NULL
   AND fpf."DATA_ACTUAL_END_DATE" IS NOT NULL
   AND fpf."ACCOUNT_RK" IS NOT NULL
   AND fpf."ACCOUNT_NUMBER" IS NOT NULL
   AND fpf."CHAR_TYPE" IS NOT NULL
   AND fpf."CURRENCY_RK" IS NOT NULL
   AND fpf."CURRENCY_CODE" IS NOT NULL; 
, parameters: None
[2025-01-07T10:06:44.649+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: ОШИБКА:  функция to_date(date, unknown) не существует
LINE 11:    to_date(fpf."DATA_ACTUAL_DATE", 'dd.mm.YYYY')
            ^
HINT:  Функция с данными именем и типами аргументов не найдена. Возможно, вам следует добавить явные приведения типов.

[2025-01-07T10:06:44.658+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=insert_date, task_id=sql_md_account_d, execution_date=20250107T095133, start_date=20250107T100644, end_date=20250107T100644
[2025-01-07T10:06:44.668+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 775 for task sql_md_account_d (ОШИБКА:  функция to_date(date, unknown) не существует
LINE 11:    to_date(fpf."DATA_ACTUAL_DATE", 'dd.mm.YYYY')
            ^
HINT:  Функция с данными именем и типами аргументов не найдена. Возможно, вам следует добавить явные приведения типов.
; 668)
[2025-01-07T10:06:44.695+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-07T10:06:44.715+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
