[2025-01-12T15:02:26.277+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T15:02:24.361713+00:00 [queued]>
[2025-01-12T15:02:26.286+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T15:02:24.361713+00:00 [queued]>
[2025-01-12T15:02:26.286+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-12T15:02:26.400+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): create_log_sheme> on 2025-01-12 15:02:24.361713+00:00
[2025-01-12T15:02:26.405+0000] {standard_task_runner.py:60} INFO - Started process 3177 to run task
[2025-01-12T15:02:26.408+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'create_log_sheme', 'manual__2025-01-12T15:02:24.361713+00:00', '--job-id', '2307', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp2qa8iene']
[2025-01-12T15:02:26.411+0000] {standard_task_runner.py:88} INFO - Job 2307: Subtask create_log_sheme
[2025-01-12T15:02:26.449+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.create_log_sheme manual__2025-01-12T15:02:24.361713+00:00 [running]> on host 711845a6becd
[2025-01-12T15:02:26.512+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='create_log_sheme' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T15:02:24.361713+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T15:02:24.361713+00:00'
[2025-01-12T15:02:26.513+0000] {sql.py:276} INFO - Executing: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(100) not null
);
[2025-01-12T15:02:26.519+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T15:02:26.526+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T15:02:26.567+0000] {sql.py:450} INFO - Running statement: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(100) not null
);, parameters: None
[2025-01-12T15:02:26.578+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_date, task_id=create_log_sheme, execution_date=20250112T150224, start_date=20250112T150226, end_date=20250112T150226
[2025-01-12T15:02:26.582+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T15:02:26.616+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO log.logt (execution_datetime, event_datetime, event_name)
        VALUES ('2025-01-12 15:02:24.361713', '2025-01-12T15:02:26.579260', 'create_log_sheme');
    , parameters: None
[2025-01-12T15:02:26.619+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-12T15:02:26.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-12T15:02:26.689+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
