[2025-01-12T14:44:18.444+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T14:44:16.386083+00:00 [queued]>
[2025-01-12T14:44:18.452+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T14:44:16.386083+00:00 [queued]>
[2025-01-12T14:44:18.453+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-12T14:44:18.582+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): create_log_sheme> on 2025-01-12 14:44:16.386083+00:00
[2025-01-12T14:44:18.588+0000] {standard_task_runner.py:60} INFO - Started process 2758 to run task
[2025-01-12T14:44:18.590+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'create_log_sheme', 'manual__2025-01-12T14:44:16.386083+00:00', '--job-id', '2256', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpei7akjzt']
[2025-01-12T14:44:18.593+0000] {standard_task_runner.py:88} INFO - Job 2256: Subtask create_log_sheme
[2025-01-12T14:44:18.631+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.create_log_sheme manual__2025-01-12T14:44:16.386083+00:00 [running]> on host 711845a6becd
[2025-01-12T14:44:18.694+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='create_log_sheme' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T14:44:16.386083+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T14:44:16.386083+00:00'
[2025-01-12T14:44:18.696+0000] {sql.py:276} INFO - Executing: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(30) not null
);
[2025-01-12T14:44:18.702+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T14:44:18.711+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T14:44:18.753+0000] {sql.py:450} INFO - Running statement: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(30) not null
);, parameters: None
[2025-01-12T14:44:18.767+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_date, task_id=create_log_sheme, execution_date=20250112T144416, start_date=20250112T144418, end_date=20250112T144418
[2025-01-12T14:44:18.771+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T14:44:18.813+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO log.logt (execution_datetime, event_datetime, event_name)
        VALUES ('2025-01-12 14:44:16.386083', '2025-01-12T14:44:18.768348', 'create_log_sheme');
    , parameters: None
[2025-01-12T14:44:18.816+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-12T14:44:18.844+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-12T14:44:18.867+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
